= Mémo design system
@CherOliv
2022-01-09 (MAJ 04/05/2025)
:jbake-title: Mémo design system
:jbake-type: post
:jbake-tags: blog, ticket, design system
:jbake-status: published
:jbake-date: 2022-01-09
:summary: Simple mémo des liens utiles et des références dans le design system

== Tools

.*Illustrations*

https://undraw.co/[undraw.co]:: Illustrations open source pour toutes les idées que vous pouvez imaginer et créer.
https://absurd.design/[absurd.design]:: Des illustrations absurdes qui ont du sens.
https://drawkit.com/[drawkit.com]:: Magnifiques illustrations gratuites. Mises à jour hebdomadaires.
https://icons8.com/[icons8.com]:: Icons, illustrations, photos, music, and design tools.
https://blush.design/[blush.design]:: Icônes, illustrations, photos, musique et outils de conception.
https://www.humaaans.com/[humaaans.com]:: Mélangez et assortissez des illustrations de personnes avec une bibliothèque de conception.

.*Couleurs*

https://coolors.co/[coolors.co]:: Le générateur de schémas de couleurs ultra-rapide !

.*Tendances*

https://fr.pinterest.com[pinterest]:: Découverte visuelle d'idées : images, vidéos, collections thématiques.
https://dribbble.com[Dribble]:: Plateforme pour designers partageant leurs créations et interagissant.

.*UX/UI et Design Systems*

https://material.io/[Google Material Design]:: Système de design de Google pour des interfaces utilisateur unifiées et adaptables.
https://developer.apple.com/design/human-interface-guidelines/[Apple Human Interface Guidelines]:: Recommandations d'Apple pour concevoir des applications iOS et macOS intuitives.
https://www.uxpin.com/[UXPin]:: Plateforme de design et de collaboration pour créer des prototypes et des design systems.
https://www.frontify.com/[Frontify]:: Plateforme de gestion de marque et de design systems pour assurer la cohérence.
https://designsystemsrepo.com/design-systems/[Design Systems Repo]:: Collection de ressources et d'exemples de design systems pour l'inspiration.

.*Développement Frontend*

https://htmlcheatsheet.com[htmlcheatsheet.com, window = "_blank"]:: HTML Cheatsheet
https://fontawesome.com[fontawesome.com, window = "_blank"]:: bibliothèque d'icones
https://www.toptal.com/designers/htmlarrows/symbols/[toptal.com/designers/htmlarrows/symbols, window = "_blank"]:: Icones natives en HTML
https://css-tricks.com/[CSS-Tricks]:: Incontournable pour CSS, avec des articles, tutoriels et astuces frontend modernes.
https://www.frontendmentor.io/[Frontend Mentor]:: Défis de code frontend basés sur des projets réels pour améliorer vos compétences.
https://dev.to/[Dev.to]:: Communauté de développeurs pour partager des articles, tutoriels et projets.
https://codepen.io/[CodePen]:: Éditeur de code en ligne et communauté pour partager des extraits de code et des démos.

.*Développement Frontend assisté par IA*

https://v0.dev/[v0.dev]:: v0 convertit les descriptions en langage naturel en code et interface utilisateur.
https://uizard.io/[Uizard]:: Uizard se concentre sur la transformation de maquettes (images, croquis) en code HTML, CSS et React.
https://www.usegalileo.ai/explore[usegalileo.ai]:: Galileo AI vous permet de décrire l'interface que vous souhaitez en langage naturel, et l'IA génère des designs Figma éditables.
https://play.teleporthq.io/[TeleportHQ]:: TeleportHQ est une plateforme de développement front-end low-code qui utilise l'IA pour vous aider à construire et déployer des sites web visuellement.
